/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "gpio.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define PB6_I2C_SCL_ALT_FUNC	4
#define PB7_I2C_SDA_ALT_FUNC	4

int main(void)
{
	gpio_init(GPIOC);
    gpio_pin_init(GPIOC, 13, GPIO_OUTPUT, 0);

	
	for(;;){
		gpio_togglePin(GPIOC, 13);
		for (uint32_t i =0; i < 100000; i++);
	}
}
