/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "gpio.h"
#include "uart.h"
#include "systick.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define SYSTICK_DELAY_MS	1000


/*Global Variables*/
static char uart_rx_data;
static int sysTickCount = 0;


int __io_putchar(int ch){
	UART1_write(ch);
	return ch;
}


int main(void)
{
	gpio_init(GPIOC);
    gpio_pin_init(GPIOC, 13, GPIO_OUTPUT, 0);
	UART1_init();
	systick_1hz_int();
	char y;
	
	for(;;){
		
		// y = UART1_read();
		// if (y == 'a') UART1_write('b');
		//printf("Hello\n\r");
		//systickDelayMs(2000);
	}
}

void USART1_IRQHandler(void){
	if ((USART1->SR & (1 << 5))){	//Check if Rx ready
		uart_rx_data = USART1->DR;
		UART1_write(uart_rx_data);
	}
}

void sysTick_callback(void){
	gpio_togglePin(GPIOC, 13);
}

void SysTick_Handler(void){
	sysTickCount++;
	if (sysTickCount == SYSTICK_DELAY_MS){
		sysTickCount = 0;
		sysTick_callback();
	}
		

}
