/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "gpio.h"
#include "uart.h"
#include "systick.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define SYSTICK_DELAY_MS	1000



/*Global Variables*/
static char uart_rx_data;
static int sysTickCount = 0;


void sysTick_callback(void){
	gpio_togglePin(GPIOC, 13);
	//printf("Hello\n\r");
}

void uart_tx_dma_cb(void){
	gpio_setPin(GPIOC, 13, PIN_HIGH);
}


int main(void)
{

	gpio_init(GPIOC);
    gpio_pin_init(GPIOC, 13, GPIO_OUTPUT, 0);
	UART1_init();
	systick_1hz_int();
	//dma2_stream7_init((uint32_t) msg, (uint32_t) &USART1->DR, 31);
	
	for(;;){
		
		// y = UART1_read();
		// if (y == 'a') UART1_write('b');
		//printf("Hello\n\r");
		//systickDelayMs(2000);
	}
}

void USART1_IRQHandler(void){
	if ((USART1->SR & (1 << 5))){	//Check if Rx ready
		uart_rx_data = USART1->DR;
		UART1_write(uart_rx_data);
	}
}

void SysTick_Handler(void){
	sysTickCount++;
	if (sysTickCount == SYSTICK_DELAY_MS){
		sysTickCount = 0;
		sysTick_callback();
	}
}

void DMA2_Stream7_IRQHandler(void){
	if (DMA2->HISR & (1U << 27)){		//Checking Transfer complete interrupt flag
		DMA2->HIFCR |= (1U << 27);		//Clear Interrupt Flag
		uart_tx_dma_cb();
	}
}
